# Arrays in python:


In [14]:
import array as arr
a=arr.array('d',[2,5,3])  #arr.array(datatype,values)
print(a)
for i in a:
    print(i)

array('d', [2.0, 5.0, 3.0])
2.0
5.0
3.0


## datatypes in an array:

# adding elements in an array:


In [15]:
import array as arr
def pr(a):
    print(a)
    
a=arr.array('f',[1,2,3,4,5,6])
pr(a)
a.insert(1,4)
pr(a)
a.append(10)
pr(a)

array('f', [1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
array('f', [1.0, 4.0, 2.0, 3.0, 4.0, 5.0, 6.0])
array('f', [1.0, 4.0, 2.0, 3.0, 4.0, 5.0, 6.0, 10.0])


In [16]:
print(a[3])

3.0


In [17]:
print(a[2:5])

array('f', [2.0, 3.0, 4.0])


In [18]:
print(a[2:5:2])

array('f', [2.0, 4.0])


# removing elements from array:

In [19]:
a.remove(2)
pr(a)

array('f', [1.0, 4.0, 3.0, 4.0, 5.0, 6.0, 10.0])


In [20]:
a.pop()
pr(a)

array('f', [1.0, 4.0, 3.0, 4.0, 5.0, 6.0])


In [21]:
a.append(0)
a.append(2)

In [29]:
 def findpair(arr,s):
        t=[]
        for i in range(len(arr)):
            for j in range(i+1,len(arr)):
                if arr[i]+arr[j]==s:
                    t.append((arr[i],arr[j]))
        return t
t=findpair(a,5)
print(t)


[(1.0, 4.0), (1.0, 4.0), (3.0, 2.0), (5.0, 0.0)]


In [30]:
def sumofmax_min(arr):
    return max(arr)+min(arr)

In [31]:
print(sumofmax_min(a))

6.0


In [32]:
print(a)

array('f', [1.0, 4.0, 3.0, 4.0, 5.0, 6.0, 0.0, 2.0])


In [54]:
l1= list(i for i in a)

In [55]:
print(l1)

[1.0, 4.0, 3.0, 4.0, 5.0, 6.0, 0.0, 2.0]


In [37]:
l1.sort()

In [38]:
print(l1)

[0.0, 1.0, 2.0, 3.0, 4.0, 4.0, 5.0, 6.0]


In [42]:
l1.sort(reverse=True)

In [43]:
print(l1)

[6.0, 5.0, 4.0, 4.0, 3.0, 2.0, 1.0, 0.0]


In [52]:
arr=[[3,1],[0.5,2],[1,3]]
arr.sort()

In [53]:
print(arr)

[[0.5, 2], [1, 3], [3, 1]]


In [56]:
l1

[1.0, 4.0, 3.0, 4.0, 5.0, 6.0, 0.0, 2.0]

In [59]:
l1.reverse()

In [60]:
print(l1)

[2.0, 0.0, 6.0, 5.0, 4.0, 3.0, 4.0, 1.0]


In [61]:
l2=l1[::-1]

In [62]:
print(l2)

[1.0, 4.0, 3.0, 4.0, 5.0, 6.0, 0.0, 2.0]


# 2d array:

In [71]:
a=[[1,2,3],[4,5,6],[7,8,9]]

<img src="row-major-2D.png">

so the elements are arranged linearly inmemory for a 2d array just like a normal array however the method of accessing the elements differ.

In [72]:
for i in range(len(a)):
    for j in range(len(a[0])):
        print(a[i][j],end=" ")
    print()

1 2 3 
4 5 6 
7 8 9 


In [74]:
a[1][2]=10

In [75]:
for i in range(len(a)):
    for j in range(len(a[0])):
        print(a[i][j],end=" ")
    print()

1 2 3 
4 5 10 
7 8 9 


In [76]:
del(a[1][2])

In [78]:
for i in range(len(a)):
    for j in range(len(a[0])):
        if i==1 and j==2:
            continue
        print(a[i][j],end=" ")
    print()

1 2 3 
4 5 
7 8 9 


## Reverse an array:


Given an array of integers and a position 'm'. Arrange the array in reverse order after that position.

In [83]:
def rev(arr,m):
    return arr[0:m+1]+arr[:m:-1]

In [84]:
a=[1,2,3,4,5,6]
m=3
print(rev(a,m))

[1, 2, 3, 4, 6, 5]


# Intersection of two sorted arrays  

#### Given two arrays A and B of size 'n'  and 'm' respectively. Both these are sorted in non decreasing order. You have to find the intersection of these two arrays

In [3]:
def find_int(arr1,arr2):
    i,j=0,0
    r=[]
    while i<len(arr1) and j<len(arr2):
        if arr1[i]==arr2[j]:
            r.append(arr1[i])
            i+=1
            j+=1
        elif arr1[i]<arr2[j]:
            i+=1
            
        else:j+=1
            
    return r
            

In [5]:
a=[1,1,2,3,5,5,7,8,9,9,9,10]
b=[2,3,5,7,11]
print(find_int(a,b))

[2, 3, 5, 7]


#### You have been given an int array of size 'm'. it contains only 0 1 2 .write a solution to sort this arraylist.

In [9]:
#brute approach:
def sort_012(arr):
    a=arr.count(0)
    b=arr.count(1)
    c=arr.count(2)
    
    l1=[]
    for i in range(a):
        l1.append(0)
    for i in range(b):
        l1.append(1)
    for i in range(c):
        l1.append(2)
    return l1

In [10]:
a=[0,1,0,1,1,2,0,1,0,2]

sort_012(a)


[0, 0, 0, 0, 1, 1, 1, 1, 2, 2]

##### optimised approach

In [13]:
def sort_012(arr):
    a,b=0,0
    c=len(arr)-1
    while b<=c:
        if arr[b]==0:
            arr[b],arr[a]=arr[a],arr[b]
            a+=1
            b+=1
        elif arr[b]==2:
            arr[b],arr[c]=arr[c],arr[b]
        
            c-=1
        else:
            b+=1
    return arr
    

In [14]:
arr=[1,0,2,0,0,1,0,1,2,2,0,0,1]
sort_012(arr)

[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]

In [17]:
import numpy as np

In [18]:
arr=np.array({1,2,3,4,5,6})

In [19]:
print(arr, type(arr))

{1, 2, 3, 4, 5, 6} <class 'numpy.ndarray'>


In [28]:
val=np.linspace(0,1,5)   #equal spaced elements from start to end-1 with given length

In [29]:
print(val,type(val))

[0.   0.25 0.5  0.75 1.  ] <class 'numpy.ndarray'>


here the start was 0 end was 1 and no. of elements were 5

In [31]:
t1=np.logspace(0,10,4) #equal log distributions from start to stop with given no. of elements
print(t1)

[1.00000000e+00 2.15443469e+03 4.64158883e+06 1.00000000e+10]


In [33]:
v2=np.arange(1,20,3) #start to end with given intervals
print(v2)

[ 1  4  7 10 13 16 19]


In [36]:
zer=np.zeros((6,3), int)

In [37]:
print(zer)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [38]:
onez=np.ones((2,3),int)

In [39]:
print(onez)

[[1 1 1]
 [1 1 1]]


# Matrix:

In [69]:
arr=[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]


In [75]:
arr[2:4]   #slicing returns another 2d list

[[7, 8, 9], [10, 11, 12]]

In [76]:
arr[2:4][0]

[7, 8, 9]

In [77]:
arr[2:4][0][1]

8

In [78]:
arr[3][1]

11

In [80]:
import array as arr
a=arr.array([[1,2,3,4],[2,3,4,5]]) #array module does not support multidimensional arrays

TypeError: array() argument 1 must be a unicode character, not list

In [86]:
import numpy as np
a=np.array([[1,2,0,4],[2,3,5,6]])   #numoy does support multidimensional array

In [87]:
print(a)

[[1 2 0 4]
 [2 3 5 6]]
